### ISSUE TITLE
有空优化下一下几点内容

### ISSUE THREAD

**Issue by taotao365s** [coocssweb/react-plug#1]
- 目录结构，混乱不堪，比如常规的.idea.xml dist, node_modules等需放到ignore中
- 既然是移动端的，加上 `React.initializeTouchEvents(true)` 
- 最后写个索引页面吧，不然每次都要敲url，心累，呵呵

整体质量还是不错的，推荐大家来观摩

**Comment by coocssweb** [comment]
嗯！一直在优化。一有时间，就会回过头去优化，做的时候一直没用手机调。
今天才发现动画方面在一些浏览器上不兼容，部分内容已经添加React.initializeTouchEvents(true)。
然后就是，第一次做这种通用性的插件库，会持续的去优化，尽力做到真的通用吧.......

**Comment by taotao365s** [comment]
加油，呵呵

**Comment by zanjs** [comment]
非常帮 正在学习，可以好好向前辈学习一下，可以

**Comment by zhujunel** [comment]
下载了你的这个项目，怎么运行跑起来呢。npm run dev 报错
